export const CREATE_ADDRESS_REQUEST = "CREATE_ADDRESS_REQUEST";
export const CREATE_ADDRESS_SUCCESS = "CREATE_ADDRESS_SUCCESS";
export const CREATE_ADDRESS_FAILURE = "CREATE_ADDRESS_FAILURE";

export const GET_USER_ADDRESSES_REQUEST = "GET_USER_ADDRESSES_REQUEST";
export const GET_USER_ADDRESSES_SUCCESS = "GET_USER_ADDRESSES_SUCCESS";
export const GET_USER_ADDRESSES_FAILURE = "GET_USER_ADDRESSES_FAILURE";