export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE";

export const UPDATE_ORDER_STATUS_REQUEST = "UPDATE_ORDER_STATUS_REQUEST";
export const UPDATE_ORDER_STATUS_SUCCESS = "UPDATE_ORDER_STATUS_SUCCESS";
export const UPDATE_ORDER_STATUS_FAILURE = "UPDATE_ORDER_STATUS_FAILURE";

export const CANCEL_ORDER_REQUEST = "CANCEL_ORDER_REQUEST";
export const CANCEL_ORDER_SUCCESS = "CANCEL_ORDER_SUCCESS";
export const CANCEL_ORDER_FAILURE = "CANCEL_ORDER_FAILURE";

export const GET_ORDER_BY_ID_REQUEST = "GET_ORDER_BY_ID_REQUEST";
export const GET_ORDER_BY_ID_SUCCESS = "GET_ORDER_BY_ID_SUCCESS";
export const GET_ORDER_BY_ID_FAILURE = "GET_ORDER_BY_ID_FAILURE";

export const GET_ALL_ORDERS_BY_USER_ID_REQUEST = "GET_ALL_ORDERS_BY_USER_ID_REQUEST";
export const GET_ALL_ORDERS_BY_USER_ID_SUCCESS = "GET_ALL_ORDERS_BY_USER_ID_SUCCESS";
export const GET_ALL_ORDERS_BY_USER_ID_FAILURE = "GET_ALL_ORDERS_BY_USER_ID_FAILURE";

export const FILTER_ORDER_REQUEST = "FILTER_ORDER_REQUEST";
export const FILTER_ORDER_SUCCESS = "FILTER_ORDER_SUCCESS";
export const FILTER_ORDER_FAILURE = "FILTER_ORDER_FAILURE";

export const GET_PAYMENT_RECEIPT_URL_REQUEST = "GET_PAYMENT_RECEIPT_URL_REQUEST";
export const GET_PAYMENT_RECEIPT_URL_SUCCESS = "GET_PAYMENT_RECEIPT_URL_SUCCESS";
export const GET_PAYMENT_RECEIPT_URL_FAILURE = "GET_PAYMENT_RECEIPT_URL_FAILURE";
