export const GET_MENU_ITEM_BY_ID_REQUEST = "GET_MENU_ITEM_BY_ID_REQUEST";
export const GET_MENU_ITEM_BY_ID_SUCCESS = "GET_MENU_ITEM_BY_ID_SUCCESS";
export const GET_MENU_ITEM_BY_ID_FAILURE = "GET_MENU_ITEM_BY_ID_FAILURE";

export const GET_MENU_ITEMS_BY_RESTAURANT_ID_REQUEST = "GET_MENU_ITEMS_BY_RESTAURANT_ID_REQUEST";
export const GET_MENU_ITEMS_BY_RESTAURANT_ID_SUCCESS = "GET_MENU_ITEMS_BY_RESTAURANT_ID_SUCCESS";
export const GET_MENU_ITEMS_BY_RESTAURANT_ID_FAILURE = "GET_MENU_ITEMS_BY_RESTAURANT_ID_FAILURE";

export const FILTER_MENU_ITEMS_BY_RESTAURANT_ID_REQUEST = "FILTER_MENU_ITEMS_BY_RESTAURANT_ID_REQUEST";
export const FILTER_MENU_ITEMS_BY_RESTAURANT_ID_SUCCESS = "FILTER_MENU_ITEMS_BY_RESTAURANT_ID_SUCCESS";
export const FILTER_MENU_ITEMS_BY_RESTAURANT_ID_FAILURE = "FILTER_MENU_ITEMS_BY_RESTAURANT_ID_FAILURE";


export const GET_ADD_ON_ITEM_BY_ID_REQUEST = "GET_ADD_ON_ITEM_BY_ID_REQUEST";
export const GET_ADD_ON_ITEM_BY_ID_SUCCESS = "GET_ADD_ON_ITEM_BY_ID_SUCCESS";
export const GET_ADD_ON_ITEM_BY_ID_FAILURE = "GET_ADD_ON_ITEM_BY_ID_FAILURE";

export const GET_ADD_ON_ITEMS_BY_RESTAURANT_ID_REQUEST = "GET_ADD_ON_ITEMS_BY_RESTAURANT_ID_REQUEST";
export const GET_ADD_ON_ITEMS_BY_RESTAURANT_ID_SUCCESS = "GET_ADD_ON_ITEMS_BY_RESTAURANT_ID_SUCCESS";
export const GET_ADD_ON_ITEMS_BY_RESTAURANT_ID_FAILURE = "GET_ADD_ON_ITEMS_BY_RESTAURANT_ID_FAILURE";