export const UPDATE_ORDER_STATUS_REQUEST = "UPDATE_ORDER_STATUS_REQUEST";
export const UPDATE_ORDER_STATUS_SUCCESS = "UPDATE_ORDER_STATUS_SUCCESS";
export const UPDATE_ORDER_STATUS_FAILURE = "UPDATE_ORDER_STATUS_FAILURE";

export const GET_ORDER_BY_ID_REQUEST = "GET_ORDER_BY_ID_REQUEST";
export const GET_ORDER_BY_ID_SUCCESS = "GET_ORDER_BY_ID_SUCCESS";
export const GET_ORDER_BY_ID_FAILURE = "GET_ORDER_BY_ID_FAILURE";

export const GET_ALL_ORDERS_BY_RESTAURANT_ID_REQUEST = "GET_ALL_ORDERS_BY_RESTAURANT_ID_REQUEST";
export const GET_ALL_ORDERS_BY_RESTAURANT_ID_SUCCESS = "GET_ALL_ORDERS_BY_RESTAURANT_ID_SUCCESS";
export const GET_ALL_ORDERS_BY_RESTAURANT_ID_FAILURE = "GET_ALL_ORDERS_BY_RESTAURANT_ID_FAILURE";

export const FILTER_ORDERS_BY_RESTAURANT_ID_REQUEST = "FILTER_ORDERS_BY_RESTAURANT_ID_REQUEST";
export const FILTER_ORDERS_BY_RESTAURANT_ID_SUCCESS = "FILTER_ORDERS_BY_RESTAURANT_ID_SUCCESS";
export const FILTER_ORDERS_BY_RESTAURANT_ID_FAILURE = "FILTER_ORDERS_BY_RESTAURANT_ID_FAILURE";

