export const GET_ALL_RESTAURANTS_REQUEST = "GET_ALL_RESTAURANTS_REQUEST";
export const GET_ALL_RESTAURANTS_SUCCESS = "GET_ALL_RESTAURANTS_SUCCESS";
export const GET_ALL_RESTAURANTS_FAILURE = "GET_ALL_RESTAURANTS_FAILURE";

export const GET_RESTAURANT_BY_ID_REQUEST = "GET_RESTAURANT_BY_ID_REQUEST";
export const GET_RESTAURANT_BY_ID_SUCCESS = "GET_RESTAURANT_BY_ID_SUCCESS";
export const GET_RESTAURANT_BY_ID_FAILURE = "GET_RESTAURANT_BY_ID_FAILURE";


export const GET_OFFER_BY_ID_REQUEST = "GET_OFFER_BY_ID_REQUEST";
export const GET_OFFER_BY_ID_SUCCESS = "GET_OFFER_BY_ID_SUCCESS";
export const GET_OFFER_BY_ID_FAILURE = "GET_OFFER_BY_ID_FAILURE";

export const GET_OFFERS_BY_RESTAURANT_ID_REQUEST = "GET_OFFERS_BY_RESTAURANT_ID_REQUEST";
export const GET_OFFERS_BY_RESTAURANT_ID_SUCCESS = "GET_OFFERS_BY_RESTAURANT_ID_SUCCESS";
export const GET_OFFERS_BY_RESTAURANT_ID_FAILURE = "GET_OFFERS_BY_RESTAURANT_ID_FAILURE";


export const GET_MENU_CATEGORY_BY_ID_REQUEST = "GET_MENU_CATEGORY_BY_ID_REQUEST";
export const GET_MENU_CATEGORY_BY_ID_SUCCESS = "GET_MENU_CATEGORY_BY_ID_SUCCESS";
export const GET_MENU_CATEGORY_BY_ID_FAILURE = "GET_MENU_CATEGORY_BY_ID_FAILURE";

export const GET_ALL_MENU_CATEGORIES_FOR_RESTAURANT_REQUEST = "GET_ALL_MENU_CATEGORIES_FOR_RESTAURANT_REQUEST";
export const GET_ALL_MENU_CATEGORIES_FOR_RESTAURANT_SUCCESS = "GET_ALL_MENU_CATEGORIES_FOR_RESTAURANT_SUCCESS";
export const GET_ALL_MENU_CATEGORIES_FOR_RESTAURANT_FAILURE = "GET_ALL_MENU_CATEGORIES_FOR_RESTAURANT_FAILURE";

export const FILTER_RESTAURANTS_REQUEST = "FILTER_RESTAURANTS_REQUEST";
export const FILTER_RESTAURANTS_SUCCESS = "FILTER_RESTAURANTS_SUCCESS";
export const FILTER_RESTAURANTS_FAILURE = "FILTER_RESTAURANTS_FAILURE";


export const GET_MENU_ITEM_BY_ID_REQUEST = "GET_MENU_ITEM_BY_ID_REQUEST";
export const GET_MENU_ITEM_BY_ID_SUCCESS = "GET_MENU_ITEM_BY_ID_SUCCESS";
export const GET_MENU_ITEM_BY_ID_FAILURE = "GET_MENU_ITEM_BY_ID_FAILURE";

export const GET_MENU_ITEMS_BY_RESTAURANT_ID_REQUEST = "GET_MENU_ITEMS_BY_RESTAURANT_ID_REQUEST";
export const GET_MENU_ITEMS_BY_RESTAURANT_ID_SUCCESS = "GET_MENU_ITEMS_BY_RESTAURANT_ID_SUCCESS";
export const GET_MENU_ITEMS_BY_RESTAURANT_ID_FAILURE = "GET_MENU_ITEMS_BY_RESTAURANT_ID_FAILURE";

export const FILTER_MENU_ITEMS_BY_RESTAURANT_ID_REQUEST = "FILTER_MENU_ITEMS_BY_RESTAURANT_ID_REQUEST";
export const FILTER_MENU_ITEMS_BY_RESTAURANT_ID_SUCCESS = "FILTER_MENU_ITEMS_BY_RESTAURANT_ID_SUCCESS";
export const FILTER_MENU_ITEMS_BY_RESTAURANT_ID_FAILURE = "FILTER_MENU_ITEMS_BY_RESTAURANT_ID_FAILURE";

export const GET_MENU_BY_RESTAURANT_ID_REQUEST = "GET_MENU_BY_RESTAURANT_ID_REQUEST";
export const GET_MENU_BY_RESTAURANT_ID_SUCCESS = "GET_MENU_BY_RESTAURANT_ID_SUCCESS";
export const GET_MENU_BY_RESTAURANT_ID_FAILURE = "GET_MENU_BY_RESTAURANT_ID_FAILURE";



export const GET_ADD_ON_ITEM_BY_ID_REQUEST = "GET_ADD_ON_ITEM_BY_ID_REQUEST";
export const GET_ADD_ON_ITEM_BY_ID_SUCCESS = "GET_ADD_ON_ITEM_BY_ID_SUCCESS";
export const GET_ADD_ON_ITEM_BY_ID_FAILURE = "GET_ADD_ON_ITEM_BY_ID_FAILURE";

export const GET_ADD_ON_ITEMS_BY_RESTAURANT_ID_REQUEST = "GET_ADD_ON_ITEMS_BY_RESTAURANT_ID_REQUEST";
export const GET_ADD_ON_ITEMS_BY_RESTAURANT_ID_SUCCESS = "GET_ADD_ON_ITEMS_BY_RESTAURANT_ID_SUCCESS";
export const GET_ADD_ON_ITEMS_BY_RESTAURANT_ID_FAILURE = "GET_ADD_ON_ITEMS_BY_RESTAURANT_ID_FAILURE";

