export const CREATE_RESTAURANT_REQUEST = "CREATE_RESTAURANT_REQUEST";
export const CREATE_RESTAURANT_SUCCESS = "CREATE_RESTAURANT_SUCCESS";
export const CREATE_RESTAURANT_FAILURE = "CREATE_RESTAURANT_FAILURE";

export const UPDATE_RESTAURANT_REQUEST = "UPDATE_RESTAURANT_REQUEST";
export const UPDATE_RESTAURANT_SUCCESS = "UPDATE_RESTAURANT_SUCCESS";
export const UPDATE_RESTAURANT_FAILURE = "UPDATE_RESTAURANT_FAILURE";

export const GET_RESTAURANT_BY_ID_REQUEST = "GET_RESTAURANT_BY_ID_REQUEST";
export const GET_RESTAURANT_BY_ID_SUCCESS = "GET_RESTAURANT_BY_ID_SUCCESS";
export const GET_RESTAURANT_BY_ID_FAILURE = "GET_RESTAURANT_BY_ID_FAILURE";

export const GET_RESTAURANT_BY_USER_ID_REQUEST = "GET_RESTAURANT_BY_USER_ID_REQUEST";
export const GET_RESTAURANT_BY_USER_ID_SUCCESS = "GET_RESTAURANT_BY_USER_ID_SUCCESS";
export const GET_RESTAURANT_BY_USER_ID_FAILURE = "GET_RESTAURANT_BY_USER_ID_FAILURE";

export const UPDATE_RESTAURANT_STATUS_REQUEST = "UPDATE_RESTAURANT_STATUS_REQUEST";
export const UPDATE_RESTAURANT_STATUS_SUCCESS = "UPDATE_RESTAURANT_STATUS_SUCCESS";
export const UPDATE_RESTAURANT_STATUS_FAILURE = "UPDATE_RESTAURANT_STATUS_FAILURE";



export const CREATE_OFFER_REQUEST = "CREATE_OFFER_REQUEST";
export const CREATE_OFFER_SUCCESS = "CREATE_OFFER_SUCCESS";
export const CREATE_OFFER_FAILURE = "CREATE_OFFER_FAILURE";

export const UPDATE_OFFER_REQUEST = "UPDATE_OFFER_REQUEST";
export const UPDATE_OFFER_SUCCESS = "UPDATE_OFFER_SUCCESS";
export const UPDATE_OFFER_FAILURE = "UPDATE_OFFER_FAILURE";

export const DELETE_OFFER_REQUEST = "DELETE_OFFER_REQUEST";
export const DELETE_OFFER_SUCCESS = "DELETE_OFFER_SUCCESS";
export const DELETE_OFFER_FAILURE = "DELETE_OFFER_FAILURE";

export const GET_OFFER_BY_ID_REQUEST = "GET_OFFER_BY_ID_REQUEST";
export const GET_OFFER_BY_ID_SUCCESS = "GET_OFFER_BY_ID_SUCCESS";
export const GET_OFFER_BY_ID_FAILURE = "GET_OFFER_BY_ID_FAILURE";

export const GET_OFFERS_BY_RESTAURANT_ID_REQUEST = "GET_OFFERS_BY_RESTAURANT_ID_REQUEST";
export const GET_OFFERS_BY_RESTAURANT_ID_SUCCESS = "GET_OFFERS_BY_RESTAURANT_ID_SUCCESS";
export const GET_OFFERS_BY_RESTAURANT_ID_FAILURE = "GET_OFFERS_BY_RESTAURANT_ID_FAILURE";



export const CREATE_MENU_CATEGORY_REQUEST = "CREATE_MENU_CATEGORY_REQUEST";
export const CREATE_MENU_CATEGORY_SUCCESS = "CREATE_MENU_CATEGORY_SUCCESS";
export const CREATE_MENU_CATEGORY_FAILURE = "CREATE_MENU_CATEGORY_FAILURE";

export const UPDATE_MENU_CATEGORY_REQUEST = "UPDATE_MENU_CATEGORY_REQUEST";
export const UPDATE_MENU_CATEGORY_SUCCESS = "UPDATE_MENU_CATEGORY_SUCCESS";
export const UPDATE_MENU_CATEGORY_FAILURE = "UPDATE_MENU_CATEGORY_FAILURE";

export const DELETE_MENU_CATEGORY_REQUEST = "DELETE_MENU_CATEGORY_REQUEST";
export const DELETE_MENU_CATEGORY_SUCCESS = "DELETE_MENU_CATEGORY_SUCCESS";
export const DELETE_MENU_CATEGORY_FAILURE = "DELETE_MENU_CATEGORY_FAILURE";

export const GET_MENU_CATEGORY_BY_ID_REQUEST = "GET_MENU_CATEGORY_BY_ID_REQUEST";
export const GET_MENU_CATEGORY_BY_ID_SUCCESS = "GET_MENU_CATEGORY_BY_ID_SUCCESS";
export const GET_MENU_CATEGORY_BY_ID_FAILURE = "GET_MENU_CATEGORY_BY_ID_FAILURE";

export const GET_ALL_MENU_CATEGORIES_FOR_RESTAURANT_REQUEST = "GET_ALL_MENU_CATEGORIES_FOR_RESTAURANT_REQUEST";
export const GET_ALL_MENU_CATEGORIES_FOR_RESTAURANT_SUCCESS = "GET_ALL_MENU_CATEGORIES_FOR_RESTAURANT_SUCCESS";
export const GET_ALL_MENU_CATEGORIES_FOR_RESTAURANT_FAILURE = "GET_ALL_MENU_CATEGORIES_FOR_RESTAURANT_FAILURE";

