export const GET_ALL_NOTIFICATIONS_REQUEST = "GET_ALL_NOTIFICATIONS_REQUEST";
export const GET_ALL_NOTIFICATIONS_SUCCESS = "GET_ALL_NOTIFICATIONS_SUCCESS";
export const GET_ALL_NOTIFICATIONS_FAILURE = "GET_ALL_NOTIFICATIONS_FAILURE";

export const GET_NOTIFICATION_COUNT_REQUEST = "GET_NOTIFICATION_COUNT_REQUEST";
export const GET_NOTIFICATION_COUNT_SUCCESS = "GET_NOTIFICATION_COUNT_SUCCESS";
export const GET_NOTIFICATION_COUNT_FAILURE = "GET_NOTIFICATION_COUNT_FAILURE";

export const GET_NOTIFICATION_BY_ID_REQUEST = "GET_NOTIFICATION_BY_ID_REQUEST";
export const GET_NOTIFICATION_BY_ID_SUCCESS = "GET_NOTIFICATION_BY_ID_SUCCESS";
export const GET_NOTIFICATION_BY_ID_FAILURE = "GET_NOTIFICATION_BY_ID_FAILURE";

export const UPDATE_NOTIFICATION_STATUS_REQUEST = "UPDATE_NOTIFICATION_STATUS_REQUEST";
export const UPDATE_NOTIFICATION_STATUS_SUCCESS = "UPDATE_NOTIFICATION_STATUS_SUCCESS";
export const UPDATE_NOTIFICATION_STATUS_FAILURE = "UPDATE_NOTIFICATION_STATUS_FAILURE";

export const FILTER_NOTIFICATION_REQUEST = "FILTER_NOTIFICATION_REQUEST";
export const FILTER_NOTIFICATION_SUCCESS = "FILTER_NOTIFICATION_SUCCESS";
export const FILTER_NOTIFICATION_FAILURE = "FILTER_NOTIFICATION_FAILURE";